CHANGELOG.md
source/Tests/QA/ResourceSchema.common.Tests.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/7)

fixing the skip logic to not get creds on non-windows

---

CHANGELOG.md
source/Tests/QA/ScriptFiles.common.Tests.ps1
source/Tests/QA/SpellCheck.common.Tests.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/9)

making spellcheck pending and fix scriptfiles

---

CHANGELOG.md
source/Tests/QA/ScriptFiles.common.Tests.ps1
source/Tests/SpellCheck.common.Tests.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/11)

trying to fix spellcheck & scriptfiles

---

CHANGELOG.md
source/Public/Initialize-TestEnvironment.ps1

@gaelcolas Shall we just release this to a preview, and I will change to use the preview.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/19)

Temporarily remove Admin-check in Initialize-TestEnvironment.

---

CHANGELOG.md
build.yaml
source/Public/Initialize-TestEnvironment.ps1
source/Public/Invoke-DscResourceTest.ps1
tests/Unit/Public/Invoke-DscResourceTest.Tests.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/24)

re-adding QA tests & fixing invoke dscresourcetest by Path

---

CHANGELOG.md
source/Tests/QA/Localization.common.Tests.ps1

This PR adds the QA Localization test from the DscResource.Tests module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/26)

Add QA Localization Test

---

CHANGELOG.md

I merged Changelog update PR AFTER merging some changes, so this will only set the record straight for next full release ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/31)

fixing the changelog that I broke

---

CHANGELOG.md
CODE_OF_CONDUCT.md
source/Tests/QA/RelativePathLength.common.Tests.ps1

Added a ModuleBase property to the `$allModulesFiles` to check with their respectvie ModuleBase, and calculate the Relative path based on this.
Fixes #34
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/35)

Fix relativepathlength

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/36)

fixing issues introduced with changelog

---

CHANGELOG.md
source/Private/Get-FunctionDefinitionAst.ps1
source/Tests/QA/Changelog.common.Tests.ps1
source/Tests/QA/ExampleFiles.common.Tests.ps1
source/Tests/QA/FileFormatting.common.Tests.ps1
source/Tests/QA/Localization.common.Tests.ps1
source/Tests/QA/MarkdownLinks.common.Tests.ps1
source/Tests/QA/ModuleFiles.common.Tests.ps1
source/Tests/QA/ModuleManifest.common.Tests.ps1
source/Tests/QA/PSSAResource.common.Tests.ps1
source/Tests/QA/Psm1Parsing.common.Tests.ps1
source/Tests/QA/PublishExampleFiles.Tests.ps1
source/Tests/QA/RelativePathLength.common.Tests.ps1
source/Tests/QA/ResourceSchema.common.Tests.ps1
source/Tests/QA/ScriptFiles.common.Tests.ps1
source/Tests/SpellCheck.common.Tests.ps1
source/potential/Tests/ExampleFiles.common.Tests.ps1
source/potential/Tests/ExampleToPlublish.common.Tests.ps1
source/potential/Tests/MarkdownLinks.common.Tests.ps1
tests/Unit/Private/Get-FunctionDefinitionAst.Tests.ps1
tests/Unit/Private/Test-ConfigurationName.Tests.ps1
tests/Unit/Private/Test-FileContainsClassResource.Tests.ps1
tests/Unit/Private/Test-FileHasByteOrderMark.Tests.ps1
tests/Unit/Private/Test-FileInUnicode.Tests.ps1
tests/Unit/Private/Test-ModuleContainsClassResource.Tests.ps1
tests/Unit/Private/Test-ModuleContainsScriptResource.Tests.ps1

- Updated QA tests to follow style guideline.
- Added a 'Because' to the change log test.
- Moved an entry in the CHANGELOG.md that got into the wrong place on the last PR merge.
- Added a little more air in the code at some places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/52)

Updated QA tests to follow style guideline

---

CHANGELOG.md
source/Public/Invoke-DscResourceTest.ps1

This is one issue with the CI/CD build right now. The other is in Sampler and a PR will be opened for that one also.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/79)

Updated calls to PsBoundParameters for have Filter

---

CHANGELOG.md
source/Tests/QA/ModuleManifest.common.Tests.ps1

- Remove Test Manifest has Class based resource in nested modules ( [issue #85](https://github.com/dsccommunity/DscResource.Test/issues/85) )
- Fixes #85
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/88)

Fix Remove Test Manifest has Class based resource in nested modules - Fixes #85

---

CHANGELOG.md
source/Public/Initialize-TestEnvironment.ps1

This PR fixes an issue in Initialize-TestEnvironment
- Fixes #97
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/98)

Fixing issue in Initialize-TestEnvironment (#97)

---

CHANGELOG.md
source/Public/Invoke-DscResourceTest.ps1

- Fix issue with running pester 4 HQRM test after preview release `v0.15.0-preview0002`.
- Style changes in code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/102)

Fix issue with running pester 4 HQRM test

---

CHANGELOG.md
GitVersion.yml
README.md
azure-pipelines.yml
source/DscResource.Test.psd1
tests/QA/module.tests.ps1

- Fixes #104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/105)

Updated pipeline files to support change of default branch to main

---

CHANGELOG.md
build.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/108)

Fix build.yaml

---

CHANGELOG.md
build.yaml
source/tasks/Fail_Build_If_HQRM_Tests_Failed.build.ps1
source/tasks/Invoke_HQRM_Tests.build.ps1

- Refactoring all taks to initiate variable with Set-SamplerTaskVariable script issue#110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dscresource.test/111)

Refactoring all taks to initiate variable with Set-SamplerTaskVariable script issue#110

---

CHANGELOG.md
README.md
azure-pipelines.yml
source/Private/Get-SystemExceptionRecord.ps1
source/Public/Get-InvalidOperationRecord.ps1
source/Public/Get-InvalidResultRecord.ps1
source/Public/Get-ObjectNotFoundRecord.ps1
tests/Unit/Private/Get-SystemExceptionRecord.Tests.ps1
tests/Unit/Public/Get-ObjectNotFoundRecord.Tests.ps1

Remove alias `Get-ObjectNotFoundRecord` from `Get-InvalidResultRecord`. 
Create private command `Get-SystemExceptionRecord`.
Update `Get-InvalidOperationRecord`, `Get-InvalidResultRecord` and `Get-ObjectNotFoundRecord` to use `Get-SystemExceptionRecord`.
- Fixes #126 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Test/131)

Remove alias `Get-ObjectNotFoundRecord` from `Get-InvalidResultRecord`

---

CHANGELOG.md
source/Tests/QA/PSSAResource.common.v4.Tests.ps1

Use correct variable for rule suppression.
Fixes #96 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Test/132)

PSSA QA Tests: Make rule suppression work

---

CHANGELOG.md
README.md
source/Public/Get-InvalidArgumentRecord.ps1
tests/Unit/Public/Get-InvalidArgumentRecord.Tests.ps1
tests/Unit/Public/Get-InvalidResultRecord.Tests.ps1

Add commonly used TestHelper `Get-InvalidArgumentRecord`. Duplicate code can then be removed from multiple Dsc Modules.
- Fixes #134
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Test/138)

Add `Get-InvalidArgumentRecord`

---

CHANGELOG.md
README.md
Resolve-Dependency.psd1
build.yaml
source/Tests/QA/MarkdownLinks.common.v4.Tests.ps1
source/Tests/QA/MarkdownLinks.common.v5.Tests.ps1
source/Tests/QA/PSSAResource.common.v4.Tests.ps1
source/Tests/QA/PSSAResource.common.v5.Tests.ps1

Update PSSAResource and MarkdownLinks to only target source files.
- Fixes #57
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Test/137)

HQRM: Only target source module for PSSA and MarkdownLinks

---

CHANGELOG.md
source/Tests/QA/ExampleFiles.common.v5.Tests.ps1
source/Tests/QA/FileFormatting.common.v5.Tests.ps1
source/Tests/QA/Localization.builtModule.v5.Tests.ps1
source/Tests/QA/Localization.common.v5.Tests.ps1
source/Tests/QA/MarkdownLinks.common.v5.Tests.ps1
source/Tests/QA/ModuleManifest.common.v5.Tests.ps1
source/Tests/QA/ModuleScriptFiles.common.v5.Tests.ps1
source/Tests/QA/PSSAResource.common.v5.Tests.ps1
source/Tests/QA/PublishExampleFiles.common.v5.Tests.ps1
source/Tests/QA/RelativePathLength.common.v5.Tests.ps1
source/Tests/QA/ResourceSchema.common.v5.Tests.ps1

- `ResourceSchema.common.v5.Tests`
- Updated to support that Pester 6 no longer allowing empty arrays in
ForEach by default.
- `PublishExampleFiles.common.v5.Tests`
- Updated to support that Pester 6 no longer allowing empty arrays in
ForEach by default.
- `ModuleManifest.common.v5.Tests`
- Updated to support that Pester 6 no longer allowing empty arrays in
ForEach by default.
- `Localization.common.v5.Tests`
- Updated to support that Pester 6 no longer allowing empty arrays in
ForEach by default.
- `Localization.builtModule.v5.Tests`
- Updated to support that Pester 6 no longer allowing empty arrays in
ForEach by default.
- `ExampleFiles.common.v5.Tests`
- Updated to support that Pester 6 no longer allowing empty arrays in
ForEach by default.
- `FileFormatting.common.v5.Tests`
- Updated …

Support Pester 6's handling of empty ForEach arrays

---

CHANGELOG.md
azure-pipelines.yml
source/Tests/QA/MarkdownLinks.common.v4.Tests.ps1

- Now the Markdown links test works with Pester 4.
- Fixes #153 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Test/154)

Fix Markdown links test  with Pester 4

---

.github/workflows/copilot-setup-steps.yml
CHANGELOG.md

- Add workflow for GitHub Copilot Agent.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DscResource.Test/166)

Add GitHub Copilot setup workflow
